package pojo;
// Generated Oct 17, 2022 2:59:36 PM by Hibernate Tools 4.3.1


import dao.BiodataSiswaDao;
import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * BiodataSiswa generated by hbm2java
 */

@ManagedBean
public class BiodataSiswa  implements java.io.Serializable {
    
     private int nis;
     private String name;
     private String gender;
     private Date birth;
     private String address;
     private int class_;
     private String religion;
     
     BiodataSiswaDao dao = new BiodataSiswaDao();

    public BiodataSiswa() {
    }

    public BiodataSiswa(int nis, String name, String gender, Date birth, String address, int class_, String religion) {
       this.nis = nis;
       this.name = name;
       this.gender = gender;
       this.birth = birth;
       this.address = address;
       this.class_ = class_;
       this.religion = religion;
    }
   
    public int getNis() {
        return this.nis;
    }
    
    public void setNis(int nis) {
        this.nis = nis;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getBirth() {
        return this.birth;
    }
    
    public void setBirth(Date birth) {
        this.birth = birth;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getClass_() {
        return this.class_;
    }
    
    public void setClass_(int class_) {
        this.class_ = class_;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    
    public String getByNis() {
        BiodataSiswa siswa = dao.getByNis(nis);
        this.nis = siswa.getNis();
        this.name = siswa.getName();
        this.gender = siswa.getGender();
        this.birth = siswa.getBirth();
        this.address = siswa.getAddress();
        this.class_ = siswa.getClass_();
        this.religion = siswa.getReligion();
        
        return "Siswa.xhtml";
    } 




}


